### ISSUE TITLE
Applying dots..

### ISSUE THREAD

**Issue by fakede-d** [AmadeusWM/nixos-dots#2]
I am trying to apply dots and not familiar with NixOS. So, how should I do that? I tried adding provided code as flake.nix but when building it gave this error:

```
warning: creating lock file '/etc/nixos/flake.lock'
error: flake 'path:/etc/nixos' does not provide attribute 'packages.x86_64-linux.nixosConfigurations."nixos".config.system.build.nixos-rebuild', 'legacyPackages.x86_64-linux.nixosConfigurations."nixos".config.system.build.nixos-rebuild' or 'nixosConfigurations."nixos".config.system.build.nixos-rebuild
```

**Comment by AmadeusWM** [comment]
You can use this flake as an input for your configuration flake (such as the one provided in the readme).

**Comment by AmadeusWM** [comment]
And then rebuild with: `home-manager switch --flake ~/path/to/flake#home-manager`
